apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cnny
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cnny
    app.kubernetes.io/part-of: ci10t-776-0095-app
  name: devfile-sample-cnny
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cnny
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cnny
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0095-tenant/ci10t-776-0095-app/devfile-sample-cnny@sha256:5d7060eec7fda091c467da4b3676cc7e9d9452c67fc3274f78168a3f0a1d5c18
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
